# Generated by Django 5.0.3 on 2024-04-01 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Waste Schedules'},
        ),
        migrations.AddField(
            model_name='waste',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasteman.schedule'),
        ),
        migrations.CreateModel(
            name='CollectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteman.wastecollector')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wasteman.schedule')),
            ],
            options={
                'verbose_name_plural': 'Collection Status',
            },
        ),
    ]
