# Generated by Django 5.0.3 on 2024-04-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0002_alter_schedule_options_waste_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waste',
            options={},
        ),
        migrations.RemoveField(
            model_name='pickupzone',
            name='location',
        ),
        migrations.AddField(
            model_name='pickupzone',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pickupzone',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
