# Generated by Django 5.0.3 on 2024-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0003_alter_waste_options_remove_pickupzone_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupzone',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickupzone',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
